version: "2"
services:
  web:
    network_mode: host
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - postgres
  postgres:
    network_mode: host
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'einfochips'
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

